# Generated by Django 4.1.4 on 2023-04-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='used_account',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='account_count',
            field=models.IntegerField(default=0),
        ),
    ]
