# Generated by Django 4.1.4 on 2023-04-04 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0002_remove_gift_date_gift_day_alter_gift_count'),
        ('user', '0003_rename_used_account_userdata_account_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='subscription',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='GiftUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
