# Generated by Django 4.1.4 on 2023-04-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_useraccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
