# Generated by Django 4.1.4 on 2023-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_useraccounts_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
