# Generated by Django 4.1.4 on 2023-04-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('date', models.IntegerField()),
                ('count', models.IntegerField()),
                ('used', models.IntegerField(default=0)),
            ],
        ),
    ]
