# Generated by Django 4.1.4 on 2023-04-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='status',
        ),
    ]
