# Generated by Django 4.1.4 on 2023-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_runmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmodel',
            name='pid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runmodel',
            name='second',
            field=models.IntegerField(default=0),
        ),
    ]
